service: aws-serverless-api-challenge 
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [EmployeesTable, Arn]
  environment:
    EMPLOYEES_TABLE: ${self:custom.tableName}


functions:
  createEmployee:
    handler: src/serverless/createEmployee.createEmployee
    events:
      - http:
          path: employees
          method: post
  deleteEmployee:
    handler: src/serverless/deleteEmployee.deleteEmployee
    events:
      - http:
          path: employees/{id}
          method: delete
  getEmployee:
    handler: src/serverless/getEmployee.getEmployee
    events:
      - http:
          path: employees/{id}
          method: get
  updateEmployee:
    handler: src/serverless/updateEmployee.updateEmployee
    events:
      - http:
          path: employees/{id}
          method: put


resources:
  Resources:
    EmployeesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}

package:
  individually: true

plugins:
  - serverless-plugin-typescript
  - serverless-esbuild

custom:
  tableName: "users-table-${sls:stage}"
  esbuild:
    bundle: true
    minify: false
