service: aws-serverless-api-challenge 
frameworkVersion: '4'

custom:
  tableName: "employees-table-${sls:stage}"

provider:
  name: aws
  runtime: nodejs20.x
  region: sa-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [EmployeesTable, Arn]
  environment:
    EMPLOYEES_TABLE: ${self:custom.tableName}


functions:
  createEmployee:
    handler: src/serverless/createEmployee.handler
    events:
      - http:
          path: employees
          method: post
  deleteEmployee:
    handler: src/serverless/deleteEmployee.handler
    events:
      - http:
          path: employees/{id}
          method: delete
  getEmployee:
    handler: src/serverless/getEmployee.handler
    events:
      - http:
          path: employees/{id}
          method: get
  updateEmployee:
    handler: src/serverless/updateEmployee.handler
    events:
      - http:
          path: employees/{id}
          method: put


resources:
  Resources:
    EmployeesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: employeeId
            AttributeType: S
        KeySchema:
          - AttributeName: employeeId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}

plugins:
  - serverless-offline

package:
  individually: true
